version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: behzod
      POSTGRES_PASSWORD: behzod_123
      POSTGRES_DB: testDb
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data